package com.businessmanager.db.dto;

public class ActionTypeDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_type.model_id
     *
     * @mbggenerated
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_type.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_type.coefficent
     *
     * @mbggenerated
     */
    private Float coefficent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_type.id
     *
     * @return the value of action_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_type.id
     *
     * @param id the value for action_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_type.model_id
     *
     * @return the value of action_type.model_id
     *
     * @mbggenerated
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_type.model_id
     *
     * @param modelId the value for action_type.model_id
     *
     * @mbggenerated
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_type.name
     *
     * @return the value of action_type.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_type.name
     *
     * @param name the value for action_type.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_type.coefficent
     *
     * @return the value of action_type.coefficent
     *
     * @mbggenerated
     */
    public Float getCoefficent() {
        return coefficent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_type.coefficent
     *
     * @param coefficent the value for action_type.coefficent
     *
     * @mbggenerated
     */
    public void setCoefficent(Float coefficent) {
        this.coefficent = coefficent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", modelId=").append(modelId);
        sb.append(", name=").append(name);
        sb.append(", coefficent=").append(coefficent);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ActionTypeDto other = (ActionTypeDto) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}