package com.businessmanager.db.dto;

import java.util.ArrayList;
import java.util.List;

public class ActionTypeCondition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table action_type
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table action_type
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table action_type
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table action_type
     *
     * @mbggenerated
     */
    private String limitClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table action_type
     *
     * @mbggenerated
     */
    private String groupByClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    public ActionTypeCondition() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        limitClause = null; 
        groupByClause = null; 
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    public void setLimitClause(String limitClause) {
         this.limitClause = limitClause; 
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    public String getLimitClause() {
         return limitClause; 
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause; 
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    public String getGroupByClause() {
         return groupByClause; 
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table action_type
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("action_type.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("action_type.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("action_type.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("action_type.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("action_type.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("action_type.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("action_type.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("action_type.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("action_type.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("action_type.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("action_type.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("action_type.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("action_type.name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("action_type.name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("action_type.name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("action_type.name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("action_type.name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("action_type.name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("action_type.name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("action_type.name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("action_type.name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("action_type.name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("action_type.name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("action_type.name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("action_type.name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("action_type.name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAIsNull() {
            addCriterion("action_type.a is null");
            return (Criteria) this;
        }

        public Criteria andAIsNotNull() {
            addCriterion("action_type.a is not null");
            return (Criteria) this;
        }

        public Criteria andAEqualTo(Float value) {
            addCriterion("action_type.a =", value, "a");
            return (Criteria) this;
        }

        public Criteria andANotEqualTo(Float value) {
            addCriterion("action_type.a <>", value, "a");
            return (Criteria) this;
        }

        public Criteria andAGreaterThan(Float value) {
            addCriterion("action_type.a >", value, "a");
            return (Criteria) this;
        }

        public Criteria andAGreaterThanOrEqualTo(Float value) {
            addCriterion("action_type.a >=", value, "a");
            return (Criteria) this;
        }

        public Criteria andALessThan(Float value) {
            addCriterion("action_type.a <", value, "a");
            return (Criteria) this;
        }

        public Criteria andALessThanOrEqualTo(Float value) {
            addCriterion("action_type.a <=", value, "a");
            return (Criteria) this;
        }

        public Criteria andAIn(List<Float> values) {
            addCriterion("action_type.a in", values, "a");
            return (Criteria) this;
        }

        public Criteria andANotIn(List<Float> values) {
            addCriterion("action_type.a not in", values, "a");
            return (Criteria) this;
        }

        public Criteria andABetween(Float value1, Float value2) {
            addCriterion("action_type.a between", value1, value2, "a");
            return (Criteria) this;
        }

        public Criteria andANotBetween(Float value1, Float value2) {
            addCriterion("action_type.a not between", value1, value2, "a");
            return (Criteria) this;
        }

        public Criteria andBIsNull() {
            addCriterion("action_type.b is null");
            return (Criteria) this;
        }

        public Criteria andBIsNotNull() {
            addCriterion("action_type.b is not null");
            return (Criteria) this;
        }

        public Criteria andBEqualTo(Float value) {
            addCriterion("action_type.b =", value, "b");
            return (Criteria) this;
        }

        public Criteria andBNotEqualTo(Float value) {
            addCriterion("action_type.b <>", value, "b");
            return (Criteria) this;
        }

        public Criteria andBGreaterThan(Float value) {
            addCriterion("action_type.b >", value, "b");
            return (Criteria) this;
        }

        public Criteria andBGreaterThanOrEqualTo(Float value) {
            addCriterion("action_type.b >=", value, "b");
            return (Criteria) this;
        }

        public Criteria andBLessThan(Float value) {
            addCriterion("action_type.b <", value, "b");
            return (Criteria) this;
        }

        public Criteria andBLessThanOrEqualTo(Float value) {
            addCriterion("action_type.b <=", value, "b");
            return (Criteria) this;
        }

        public Criteria andBIn(List<Float> values) {
            addCriterion("action_type.b in", values, "b");
            return (Criteria) this;
        }

        public Criteria andBNotIn(List<Float> values) {
            addCriterion("action_type.b not in", values, "b");
            return (Criteria) this;
        }

        public Criteria andBBetween(Float value1, Float value2) {
            addCriterion("action_type.b between", value1, value2, "b");
            return (Criteria) this;
        }

        public Criteria andBNotBetween(Float value1, Float value2) {
            addCriterion("action_type.b not between", value1, value2, "b");
            return (Criteria) this;
        }

        public Criteria andCIsNull() {
            addCriterion("action_type.c is null");
            return (Criteria) this;
        }

        public Criteria andCIsNotNull() {
            addCriterion("action_type.c is not null");
            return (Criteria) this;
        }

        public Criteria andCEqualTo(Float value) {
            addCriterion("action_type.c =", value, "c");
            return (Criteria) this;
        }

        public Criteria andCNotEqualTo(Float value) {
            addCriterion("action_type.c <>", value, "c");
            return (Criteria) this;
        }

        public Criteria andCGreaterThan(Float value) {
            addCriterion("action_type.c >", value, "c");
            return (Criteria) this;
        }

        public Criteria andCGreaterThanOrEqualTo(Float value) {
            addCriterion("action_type.c >=", value, "c");
            return (Criteria) this;
        }

        public Criteria andCLessThan(Float value) {
            addCriterion("action_type.c <", value, "c");
            return (Criteria) this;
        }

        public Criteria andCLessThanOrEqualTo(Float value) {
            addCriterion("action_type.c <=", value, "c");
            return (Criteria) this;
        }

        public Criteria andCIn(List<Float> values) {
            addCriterion("action_type.c in", values, "c");
            return (Criteria) this;
        }

        public Criteria andCNotIn(List<Float> values) {
            addCriterion("action_type.c not in", values, "c");
            return (Criteria) this;
        }

        public Criteria andCBetween(Float value1, Float value2) {
            addCriterion("action_type.c between", value1, value2, "c");
            return (Criteria) this;
        }

        public Criteria andCNotBetween(Float value1, Float value2) {
            addCriterion("action_type.c not between", value1, value2, "c");
            return (Criteria) this;
        }

        public Criteria andNameLikeInsensitive(String value) {
            addCriterion("upper(action_type.name) like", value.toUpperCase(), "name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table action_type
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table action_type
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}