package com.businessmanager.db.dto;

public class BusinessProviderPk {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_provider.business_id
     *
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_provider.provider_id
     *
     * @mbggenerated
     */
    private Integer providerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_provider.business_id
     *
     * @return the value of business_provider.business_id
     *
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_provider.business_id
     *
     * @param businessId the value for business_provider.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_provider.provider_id
     *
     * @return the value of business_provider.provider_id
     *
     * @mbggenerated
     */
    public Integer getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_provider.provider_id
     *
     * @param providerId the value for business_provider.provider_id
     *
     * @mbggenerated
     */
    public void setProviderId(Integer providerId) {
        this.providerId = providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_provider
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", businessId=").append(businessId);
        sb.append(", providerId=").append(providerId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_provider
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BusinessProviderPk other = (BusinessProviderPk) that;
        return (this.getBusinessId() == null ? other.getBusinessId() == null : this.getBusinessId().equals(other.getBusinessId()))
            && (this.getProviderId() == null ? other.getProviderId() == null : this.getProviderId().equals(other.getProviderId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_provider
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBusinessId() == null) ? 0 : getBusinessId().hashCode());
        result = prime * result + ((getProviderId() == null) ? 0 : getProviderId().hashCode());
        return result;
    }
}