package com.businessmanager.db.dao;

import com.businessmanager.db.dto.ActionTypeCondition;
import com.businessmanager.db.dto.ActionTypeDto;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface ActionTypeDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    int countByExample(ActionTypeCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    int deleteByExample(ActionTypeCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    int insert(ActionTypeDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    int insertSelective(ActionTypeDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    List<ActionTypeDto> selectByExample(ActionTypeCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    ActionTypeDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ActionTypeDto record, @Param("example") ActionTypeCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ActionTypeDto record, @Param("example") ActionTypeCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActionTypeDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActionTypeDto record);

    /**
     * Custom generated method to insert list.
     * @mbggenerated
     */
    void insertList(@Param("recordList") List<ActionTypeDto> values);
}