package com.businessmanager.db.dao;

import com.businessmanager.db.dto.BusinessProductCondition;
import com.businessmanager.db.dto.BusinessProductPk;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface BusinessProductDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbggenerated
     */
    int countByExample(BusinessProductCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbggenerated
     */
    int deleteByExample(BusinessProductCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BusinessProductPk key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbggenerated
     */
    int insert(BusinessProductPk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbggenerated
     */
    int insertSelective(BusinessProductPk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbggenerated
     */
    List<BusinessProductPk> selectByExample(BusinessProductCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BusinessProductPk record, @Param("example") BusinessProductCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BusinessProductPk record, @Param("example") BusinessProductCondition example);

    /**
     * Custom generated method to insert list.
     * @mbggenerated
     */
    void insertList(@Param("recordList") List<BusinessProductPk> values);
}