package com.businessmanager.db.dao;

import com.businessmanager.db.dto.BusinessMarketCondition;
import com.businessmanager.db.dto.BusinessMarketPk;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface BusinessMarketDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_market
     *
     * @mbggenerated
     */
    int countByExample(BusinessMarketCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_market
     *
     * @mbggenerated
     */
    int deleteByExample(BusinessMarketCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_market
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BusinessMarketPk key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_market
     *
     * @mbggenerated
     */
    int insert(BusinessMarketPk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_market
     *
     * @mbggenerated
     */
    int insertSelective(BusinessMarketPk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_market
     *
     * @mbggenerated
     */
    List<BusinessMarketPk> selectByExample(BusinessMarketCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_market
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BusinessMarketPk record, @Param("example") BusinessMarketCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_market
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BusinessMarketPk record, @Param("example") BusinessMarketCondition example);

    /**
     * Custom generated method to insert list.
     * @mbggenerated
     */
    void insertList(@Param("recordList") List<BusinessMarketPk> values);
}