package com.businessmanager.db.dao;

import com.businessmanager.db.dto.DestinationCondition;
import com.businessmanager.db.dto.DestinationDto;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface DestinationDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destination
     *
     * @mbggenerated
     */
    int countByExample(DestinationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destination
     *
     * @mbggenerated
     */
    int deleteByExample(DestinationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destination
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destination
     *
     * @mbggenerated
     */
    int insert(DestinationDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destination
     *
     * @mbggenerated
     */
    int insertSelective(DestinationDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destination
     *
     * @mbggenerated
     */
    List<DestinationDto> selectByExample(DestinationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destination
     *
     * @mbggenerated
     */
    DestinationDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destination
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DestinationDto record, @Param("example") DestinationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destination
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DestinationDto record, @Param("example") DestinationCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destination
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DestinationDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destination
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DestinationDto record);

    /**
     * Custom generated method to insert list.
     * @mbggenerated
     */
    void insertList(@Param("recordList") List<DestinationDto> values);
}