package com.businessmanager.db.dao;

import com.businessmanager.db.dto.MarketCondition;
import com.businessmanager.db.dto.MarketDto;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface MarketDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbggenerated
     */
    int countByExample(MarketCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbggenerated
     */
    int deleteByExample(MarketCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbggenerated
     */
    int insert(MarketDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbggenerated
     */
    int insertSelective(MarketDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbggenerated
     */
    List<MarketDto> selectByExample(MarketCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbggenerated
     */
    MarketDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MarketDto record, @Param("example") MarketCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MarketDto record, @Param("example") MarketCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MarketDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MarketDto record);

    /**
     * Custom generated method to insert list.
     * @mbggenerated
     */
    void insertList(@Param("recordList") List<MarketDto> values);

    /**
     * Select markets by business id.
     * @param businessId  User business ID.
     * @return List of markets dto.
     */
    List<MarketDto> selectMarketsByBusinessId(@Param("businessId") Integer businessId);
}